
#WORKSPACE_FILES#main#MIN#.js

applySavedTheme()

#WORKSPACE_FILES#normailize#MIN#.css
#WORKSPACE_FILES#main#MIN#.css


/**For Modal Pages */
form#wwvFlowForm {
    min-height: 100vh;
    background-color: var(--bg-clr-1);
    color: var(--t-clr-1);
}



/* For Full Pages */
#PageContentContainer{
    display: none;
}


delete-btn
apply-btn

btn-style-wa

UPDATE_DEFAULT_VALUE
BEGIN
    IF :P25_MAIN_BRANCH = 'Y' THEN
        UPDATE COMPANY_BRANCHES 
        SET MAIN_BRANCH = 'N';
 
        UPDATE COMPANY_BRANCHES 
        SET MAIN_BRANCH = 'Y' 
        WHERE BRANCH_ID = :P25_BRANCH_ID;
    END IF;
END;

SELECT EMP_ID
FROM app_users
WHERE UPPER(:APP_USER) = UPPER(EMP_NAME)


WHERE tr.DELETED <> 1
DECODE(tr.DEFAULT_VALUE, 'Y','Yes','No') "Default",
DECODE(tr.TR_ENABLED, 'Y', 'Active','Inactive') Status
DECODE(et.POSTED_REC, '1','Posted', 'Not Posted')

(select cb.BRANCH_NAME from COMPANY_BRANCHES cb where cb.BRANCH_ID = u.EMP_BRANCH) EMP_BRANCH,
(select au.EMP_NAME from app_users au where au.EMP_ID = u.CREATED_BY) CREATED_BY,
(select au.EMP_NAME from app_users au where au.EMP_ID = u.UPDATED_BY) UPDATED_BY,

(select cb.BRANCH_NAME from COMPANY_BRANCHES cb where cb.BRANCH_ID = al.COMPANY_ID) COMPANY
(select alca.C_ACC_NAME from APP_LEDGER_CHILD_ACCS alca where alca.C_ACC_ID =al.ENTRY_ACC ) Entry_Account,
(select alca.C_ACC_NAME from APP_LEDGER_CHILD_ACCS alca where alca.C_ACC_ID =tr.C_CHILD_ACCOUNT ) "Account",




INSERT INTO SALES_INVOICE_LINES (INV_ID,ITEM_ID,QTY,PRICE,TOTAL_BEFORE_TAX,CREATED_BY,UPDATED_BY,CREATION_DATE,UPDATE_DATE,DELETED,LINE_TYPE,TOTAL_AFTER_TAX,TAX_AMT,TAX_RATE,TAX_RATE_ID,LINE_DISCOUNT,LINE_OFFER,POSTED_REC)
SELECT INV_ID,ITEM_ID,QTY,PRICE,TOTAL_BEFORE_TAX,CREATED_BY,UPDATED_BY,CREATION_DATE,UPDATE_DATE,DELETED,LINE_TYPE,TOTAL_AFTER_TAX,TAX_AMT,TAX_RATE,TAX_RATE_ID,LINE_DISCOUNT,LINE_OFFER,POSTED_REC
FROM SALES_INVOICE_LINES

INSERT INTO SALES_INV_PAY(CUST_ID,PAYMENT_AMT,INV_ID,CREATED_BY,UPDATED_BY,CREATION_DATE,UPDATE_DATE,DELETED,PAYMENT_DATE,PAY_METHOD,POSTED_REC)
SELECT CUST_ID,PAYMENT_AMT,INV_ID,CREATED_BY,UPDATED_BY,CREATION_DATE,UPDATE_DATE,DELETED,PAYMENT_DATE,PAY_METHOD,POSTED_REC FROM SALES_INV_PAY

SELECT COUNT(*) FROM SALES_INV_PAY
SELECT COUNT(*) FROM SALES_INVOICE_LINES


BEGIN
    EXECUTE IMMEDIATE
        'update SALES_INV_PAY set POSTED_REC= 0';
    EXECUTE IMMEDIATE
        'update SALES_INVOICE_LINES set POSTED_REC= 0';
    EXECUTE IMMEDIATE
        'update SALES_INV_HEADER set POSTED_REC= 0';
    EXECUTE IMMEDIATE
        'update APP_EXPENSES set LAST_GL_CREATED=null';
    EXECUTE IMMEDIATE
        'update EMP_TRANSACTIONS set POSTED_REC=0';
    EXECUTE IMMEDIATE
        'truncate table APP_LOG';
    EXECUTE IMMEDIATE
        'truncate table APP_LEDGER';
    EXECUTE IMMEDIATE
        'truncate table CASH_ENTRIES';

    EXECUTE IMMEDIATE
        'truncate table PURCHASE_INVOICE_LINES';
    EXECUTE IMMEDIATE
        'truncate table PURCHASE_INV_HEADER';

    EXECUTE IMMEDIATE
        'truncate table SALES_INVOICE_LINES';
    EXECUTE IMMEDIATE
        'truncate table SALES_INV_PAY';
    EXECUTE IMMEDIATE
        'truncate table SALES_INV_HEADER';
END